services:
  - type: web
    name: notion-deglacer
    env: go
    repo: https://github.com/mikan-tech/notion-deglacer.git
    plan: free
    buildCommand: make build
    startCommand: ./bin/deglacer
    envVars:
      - key: SLACK_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: NOTION_TOKEN
        sync: false
